### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#11]
- ~Automatic snapshot uploads.~
- [x] Pull request verification.
- [x] `master` branch testing.
- ~Dokka documentation publishing.~

**Comment by czyzby** [comment]
[This might be useful](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd).

**Comment by czyzby** [comment]
Travis no longer runs Dokka-related tasks, as it seems they were causing builds to fail due to running for too long.

**Comment by aouerfelli** [comment]
You might want to check [this](https://docs.travis-ci.com/user/deployment/pages/) out for Dokka publishing to gh-pages:
```yml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build/dokkaJavadoc
  on:
    branch: master
```
